### ISSUE TITLE
Display value of foil in !price responses as well

### ISSUE THREAD

**Issue by vaeng** [bra1n/judgebot#103]
It would be nice to have the option to know the foil price as well. I thought of doing it with "!price isolate is:foil" to narrow down the result, but that doesn't work

**Comment by bra1n** [comment]
Currently we only show the prices that Scryfall delivers, which are unfortunately not for foils. If we want to have foil prices on judgebot, we'd need to add an external pricing API. It's doable, but not an easy fix.

**Comment by bra1n** [comment]
Scryfall added (USD) Foil prices, so we have those now, too!
