### ISSUE TITLE
[Feature Request] Variable Prefix for Commands

### ISSUE THREAD

**Issue by EvoFox** [bra1n/judgebot#104]
Would it be at all possible to create a feature in which you could change the prefix of the commands from ! to another symbol?

I run a small community that uses a fair number of bots and I would like to be able to tweak the prefixes of them so that they don't overlap.

**Comment by bra1n** [comment]
Not really. Judgebot doesn't store any data for any of the servers it is on, so the only way to change the prefix would be to change it globally. Your best bet at this moment would be to simply fork the bot and run your own version with a modified prefix for your own server.

**Comment by multimeric** [comment]
This is no longer relevant with the move to slash commands. Effectively the prefix is always going to be `/` from now on (and this is true for all bots). Eventually I'm sure discord will add some QOL improvements for this too.
