### ISSUE TITLE
Some mana symbols are broken

### ISSUE THREAD

**Issue by bra1n** [bra1n/judgebot#112]
Example: 
!card apex predator
!card iona
![Bildschirmfoto 2019-07-09 um 11 11 01](https://user-images.githubusercontent.com/325521/60875507-4f13a080-a23a-11e9-939b-2164bac1df55.png)
![Bildschirmfoto 2019-07-09 um 11 11 07](https://user-images.githubusercontent.com/325521/60875509-4fac3700-a23a-11e9-8494-c218821f49ca.png)

**Comment by D4rkL1ch** [comment]
I do have the same problem on my Discord server with any card.
<img width="604" alt="Screenshot 2019-08-03 at 13 07 37" src="https://user-images.githubusercontent.com/4180274/62411180-b2051700-b5ef-11e9-85ab-5329325bd2e3.png">

**Comment by bra1n** [comment]
Finally fixed. :-)

**Comment by D4rkL1ch** [comment]
This is still happening for me, do I need to somehow "update" the bot on the server or change its settings?
<img width="624" alt="obraz" src="https://user-images.githubusercontent.com/4180274/63930217-28f8c880-ca53-11e9-812b-c3c4f7be8096.png">

**Comment by bra1n** [comment]
@D4rkL1ch I can't reproduce your issue:
![image](https://user-images.githubusercontent.com/325521/63956645-1e582680-ca87-11e9-8fe3-66afe602e9fd.png)

Did you maybe disallow external emojis in this channel / for this role? You could try removing and re-adding the bot and see if that fixes the problems. Also make sure that external emojis are allowed.
