### ISSUE TITLE
hangman

### ISSUE THREAD

**Issue by tyler3802** [bra1n/judgebot#119]
it keeps sending a message saying that must wait 3 min in between, yet i haven't used it for hours.  This keeps repeating to the point where i kicked the bot and re-installed it.  the same problem occurred.  What should i do? 
Thank you for your time,
Tyler

**Comment by bra1n** [comment]
Hey, so I just tested this feature on two different servers and it works on both. Do you still have this problem right now?

**Comment by tyler3802** [comment]
Yes

**Comment by bra1n** [comment]
Alright, I need to investigate this further. Is your server public so I can take a look at it?

**Comment by bra1n** [comment]
Since I can't reproduce it and haven't heard back from you in a while, I'll close this issue for now.
