### ISSUE TITLE
Judgebot offline

### ISSUE THREAD

**Issue by Majias** [bra1n/judgebot#124]
Hello,

Judgebot went offline in my two servers and I'm unsure why, it's been functionning accurately for over 6 months in one and over 3 years in the other. When I check other judgerelated servers, I see that judgebot is up (like the official Magic Judges Discord).
Any idea what the issue could be related to ?

Thanks

**Comment by bra1n** [comment]
Hi @Majias,
it was probably just a hickup on my server or the Discord API. I restarted the bot, please check again if it's still broken for you. If it is, I'd suggest kicking the bot and re-adding it to your server. :-)

**Comment by Majias** [comment]
Worked wonders, thank you for the help and for the great bot :)

**Comment by bra1n** [comment]
Awesome, glad that this fixed it. :-D
