### ISSUE TITLE
!hangman seems to ignore guesses after ~2m

### ISSUE THREAD

**Issue by grotlek** [bra1n/judgebot#125]
As title, the hangman command seems to ignore any guesses after ~2 minutes - a minute less than the 3m it says people have. It waits the full 3m to post the answer but for a period of time it just doesn't accept new guessed letters.

When you fix this, may I suggest that you also show the time remaining (at least at every 30 second intervals if not an actual count down).

**Comment by SantiRivera92** [comment]
The bot does not ignore any guesses after ~2 minutes. The bot ignores any guesses after anyone talks in the same room where the hangman is going on.

**Comment by bra1n** [comment]
As has been pointed out in #126 this is probably an issue of a too short timespan where the bot will listen to reactions. @TMiguelT has been working on a fix for this and I'll merge his changes soon, after which it should work better. :) People talking in the same channel where the hangman game is played does actually make the bot "forget" the ongoing game so this will be fixed, too.
