### ISSUE TITLE
Bot not reading reactions

### ISSUE THREAD

**Issue by multimeric** [bra1n/judgebot#126]
Hi,

Thanks for this great bot. However, I just installed it, but it seems to be ignoring the reacts, e.g. for hangman, and the arrows for the search. Is there a certain permission that I'm missing perhaps?

*edit:* it isn't ignoring them, it just stops listening after a very short period

**Comment by multimeric** [comment]
However, it correctly reads reactions when I PM the bot directly.

**Comment by multimeric** [comment]
I think this relates to: https://github.com/bra1n/judgebot/blob/e05a23f6183d86bb0951721773bcb579af49c48e/modules/card.js#L367-L371. You're only listening to reacts for 1 minute, and only listening for up to 20 reacts. Is it possible to bump this up? It seems a little short.

**Comment by bra1n** [comment]
Hi @TMiguelT,
you are correct in that the bot will stop listening to reactions after 1 minute. The reason for that is, that the bot is running on 3000+ servers at the same time - all powered by a single, low-performance machine. Having listeners open for a few dozen messages at the same time would overload the bot pretty fast, so I'm kinda hesitant to increase this limit, unless there's a better place where I could host the bot for free. :grimacing:

**Comment by multimeric** [comment]
Ohh that makes sense, I didn't realise you had to host discord bots yourself. The best free hosting I know about is Google Compute Engine's free tier (a single [f1-micro](https://cloud.google.com/compute/docs/machine-types) free forever), but I doubt that would be any more powerful than what you're using.

I wonder if there is merit to using a stateless compute solution like AWS Lambda or Google Cloud Functions. Google offers 2 million free invocations per month. So 2,000,000/3000 = 666 hooks per server per month. Maybe that's not enough?

At least in my case I might spin up a copy of your bot just for my own server, and boost the heck out of the time limits and reaction limits.

Unrelated to the hosting issue, but there is definitely a bug relating to timing. The hangman bot is supposed to listen for 3 minutes and the search arrows are supposed to listen for 1 minute, but I've tested on my server and hangman definitely only listens for 1 minute at most. This is no doubt the same issue as #125. I had a look at the code and couldn't find any issues, but maybe try bumping discord.js to the latest version just in case that helps?

**Comment by multimeric** [comment]
After some exhausting troubleshooting, I've worked out the problem. It's not that your `time` value is wrong for the collector object, it's that your bot's cache timeout is too short.

From [this StackOverflow answer](https://stackoverflow.com/a/53102716/2148718), I realised that reactions are only handled for cached messages, and currently you're only caching messages for 60 seconds, and sweeping every 90 seconds: https://github.com/bra1n/judgebot/blob/e05a23f6183d86bb0951721773bcb579af49c48e/server.js#L27-L29 What this means is that every 1:30 minutes, the cache is cleared, and the ReactionCollector stops being able to read reactions to old messages, even if the timeout hasn't yet occurred.

In my fork I bumped this cache timeout to a massively higher value, which resolved the issue. I understand if you don't want to do that here, but if anyone else is planning to host a fork for their own server, this might be helpful.

My fork is [here](https://github.com/TMiguelT/judgebot), and one other change I made is bumping all the libraries, and then fixing a new incompatibility introduced by discord.js 12, namely that the description field in embeds can no longer contain markdown.

**Comment by bra1n** [comment]
Thanks for the investigation, that does look like a bug to me! I'll add some comments to your PR and will merge it later to the master branch.

**Comment by multimeric** [comment]
Ah unfortunately neither of my PRs actually attempt to fix this, they relate to other issues/features. But the simple fix is just setting the `messageCacheLifetime` to a number that's always >= the maximum ReactionCollector time. So for your master branch you should have `messageCacheLifetime: 60 * 3 `

**Comment by bra1n** [comment]
> Ah unfortunately neither of my PRs actually attempt to fix this, they relate to other issues/features. But the simple fix is just setting the `messageCacheLifetime` to a number that's always >= the maximum ReactionCollector time. So for your master branch you should have `messageCacheLifetime: 60 * 3 `

Yeah I saw. :D I went ahead and increased the numbers myself, after looking at your fork.
