### ISSUE TITLE
Prevent the bot from finding incorrect results

### ISSUE THREAD

**Issue by Mehtu** [bra1n/judgebot#13]
The command "!card Nix" finds a random Phoenix instead of the card Nix.

Ideas to solve this:
- If the bot finds multiple results, interpose a text comparison before the result is posted and if one card matches the query exactly, post that one.
- Prioritize results that start with the search query if no card matches it exactly.
- Prioritize results that contain the search query as a solitary word instead of a part of a word (Nix in Phoenix).

**Comment by bra1n** [comment]
Fixed with #16
