### ISSUE TITLE
Hangman Broken Again

### ISSUE THREAD

**Issue by harryfino** [bra1n/judgebot#135]
Hangman keeps throwing an error regardless of how many minutes we let pass. We've tried hours. We've already tried kicking the bot and re-inviting to no avail.

<img width="376" alt="Screen Shot 2020-06-06 at 2 15 28 PM" src="https://user-images.githubusercontent.com/1643512/83951557-3ae87280-a800-11ea-9bff-9ba56b9ecc4e.png">

**Comment by harryfino** [comment]
Running `!hangman guess <string>` seems to unstuck the game. Closing it until I can figure out how to reproduce.

**Comment by bra1n** [comment]
> Running `!hangman guess <string>` seems to unstuck the game. Closing it until I can figure out how to reproduce.

Huh, interesting. Could be a bug in the guessing code maybe? @TMiguelT

**Comment by multimeric** [comment]
Yes if you can hit me with a reproducible example I'd be happy to debug it. I suspect it's not to do with the guessing code so much as the general refactor that I did.
