### ISSUE TITLE
!cr not citing the correct rules

### ISSUE THREAD

**Issue by michaelihorwitz** [bra1n/judgebot#138]
I noticed today that I kept getting weird results from !cr, and after a bit I was arguing about some rules with someone when someone did !cr 103.2 and the bot cited rule 103.1 instead and mislabeled it as 103.2. Attached is an image of the incorrect citation.
![Judgebot issue](https://user-images.githubusercontent.com/46689098/91684300-13662500-eb25-11ea-96a4-05ba1ffac800.png)

**Comment by bra1n** [comment]
Ah yes, this was caused by outdated CR. Thanks to #140 the CR will now automatically update whenever there is a new version. :)
