### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by multimeric** [bra1n/judgebot#146]
Discord recently added "slash commands", which is a platform-supported method of defining bot commands, subcommands and arguments. It gives features like command completion, a better UI and discoverability for commands: https://discord.com/developers/docs/interactions/slash-commands.

I think this would be a great feature for judgebot. I'm happy to implement this once I get time. Currently this isn't natively supported by discord.js, so it's probably not worth starting until this PR is merged: ~~https://github.com/discordjs/discord.js/pull/5106~~ https://github.com/discordjs/discord.js/pull/5448.

**Comment by thetayloredman** [comment]
One thing: you are limited to 50 guild commands and 50 global commands.

**Comment by multimeric** [comment]
Why is this a problem? Judgebot has like 14 commands as is. If it ever grows to beyond 50 I think that subcommands could be used to shrink this number.

**Comment by thetayloredman** [comment]
Ah, okay

**Comment by bra1n** [comment]
Ooh, nice feature! Thanks for the heads-up, when they finish the linked PR I think it could be used for judgebot. However, it looks like it would need a lot of rewriting and at least the webhook approach won't work with Emoji reactions, if I'm not mistaken. So we'll have to see how an "INTERACTION_CREATE" gateway event will be handled by Discord.JS.

**Comment by multimeric** [comment]
I think the bot can respond to the interaction with a regular message sent to the channel, at which point you can listen for reactions in the normal way. So I don't think this will be a huge issue.

**Comment by bra1n** [comment]
Let's hope that's going to be the case. :-)

**Comment by thetayloredman** [comment]
It appears so.

**Comment by multimeric** [comment]
Okay slash commands are now enabled since discord.js 13.0.0 on August 6. So this feature is unblocked.

**Comment by multimeric** [comment]
Closed by #159.
