### ISSUE TITLE
"The application did not respond" when trying to search for cards from specific set.

### ISSUE THREAD

**Issue by EnoralTheOutCast** [bra1n/judgebot#174]
I am not sure if it is supposed to not work but. 
I tried to enter the following command "/card e:XLN" Just to try if it will give me cards from Ixalan set (can be any set, Ixalan is just an example here). On Scryfall it would. But when i tried to do it with Judgebot it just stuck on "judgebot is thinking" and doesn't respond.
And if i tried to specify the type like "/card t:instant e:xln" it did give me instants.

**Comment by EnoralTheOutCast** [comment]
So if Judgebot fully supports Scryfall syntax, i should be able to just use the set tag and it should return the cards from that set.
But it doesn't.

**Comment by multimeric** [comment]
Yes, it should work. I believe it's happening whenever you write a query with a very large number of results (100+). For the moment, try to avoid very general queries like that, but I'll try to work out a fix in the meantime.

**Comment by multimeric** [comment]
Okay I think this is an upstream bug from https://github.com/ChiriVulpes/scryfall-sdk/issues/52. My guess is that the bot will hang whenever the query returns more than 75 results (which is the page size).

**Comment by multimeric** [comment]
This fix has now been deployed, and seems to be working correctly.
