### ISSUE TITLE
Incorrect CR character encoding

### ISSUE THREAD

**Issue by lunakv** [bra1n/judgebot#181]
## What
If you look at the current output of the bot, it contains a bunch of malformatted characters. For example, all quotation marks are replaced with �. 

## Why
The text version of the CR is published as a WINDOWS-1252 encoded string, but by the looks of it, the CR module tries to parse it as UTF-8, which causes issues for characters outside the standard ASCII range. 

I'm not sure if VJ used to link to some pre-processed version of the doc which made this work, but on Academy Ruins the `/link` routes are just a literal 307 redirect to WotC's servers. 

## Fix?
There are two possibilities that come to mind. The simplest is to just update the `iconv` call so that the document is decoded properly. Maybe the more robust option might be to ditch most of the parsing logic altogether and load the parsed CR as a JSON directly from Academy Ruins, which is guaranteed to be UTF-8 encoded.

*Edit:* If you need a really quick bandaid solution, a UTF-8 encoded version of the current CR is at `api.academyruins.com/file/cr/UNF`

## Screenshot
![Screenshot_20221011-075816](https://user-images.githubusercontent.com/38463785/195008176-c776cd2d-7f59-4e00-9dc2-8aa571fe9fbc.png)

**Comment by lunakv** [comment]
Any update on this? It's a bit annoying to still see question boxes in almost every bot call.

**Comment by multimeric** [comment]
> Maybe the more robust option might be to ditch most of the parsing logic altogether and load the parsed CR as a JSON directly from Academy Ruins, which is guaranteed to be UTF-8 encoded.

What advantage would we gain from using Academy Ruins's parser? I'm tending towards just changing the input encoding at the moment.

**Comment by lunakv** [comment]
They are slight, but the two that I see are 
1. Not needing to do (most of) your own parsing. Granted, that may not *too* meaningful since the parsing is already implemented, but it could be seen as simplifying the project / deduplicating efforts, and would rid you of the hassles that arise in in managing your own code.
2. The API makes some guarantees about its output structure that the raw file doesn't. So if the CR changes its formatting or character encoding (again 🙂) in the future, you can rely on that stuff being handled upstream instead of having to deal with it yourself. 
3. This is not an upside per se, but a notable diffreence is that the API returns "richly formatted" text (curly quotes, proper en and em dashes, actual trademark symbols instead of `(tm)`/`(r)`, etc.). *Edit:* To clarify, this is also true of the original CR text file, but the judgebot parser strips away most of that.

It might very well be more practical for you to just to do the simple fix, but I just wanted to throw that out there as a possibility.

**Comment by lunakv** [comment]
*Speaking of stability...*

The new CR just dropped and apparently *now* the text file is in UTF-16BE! :facepalm:

**Comment by lunakv** [comment]
Which, by the way, I just found out made this a much bigger deal, since instead of just some badly rendered quotation marks, the CR now apparently fully fails to parse, because UTF-16 just rolls that way. (At least that's what appears to have happened, all my `/cr` commands started to return "No Results" responses.)

**Comment by multimeric** [comment]
That sucks. I guess if we start using Academy Ruins then at least Judgebot will be insulated from changes like that, and in the meantime Academy Ruins can implement a fix for the encoding?

**Comment by lunakv** [comment]
> in the meantime Academy Ruins can implement a fix  

I'm not quite sure what you mean by this? All content served by AR is already UTF-8 encoded, so there's no issue there. The reason this route isn't consistent is because it's just a basic 307 redirect pointing to WotC's servers, so I have really no control over what ultimately gets returned.

If you want a band-aid fix for now, I would suggest you either temporarily change the parser to load the file as UTF-16BE, or temporarily load the file from https://api.academyruins.com/file/cr/bro, which is encoded as UTF-8.

**Comment by multimeric** [comment]
How can AR both be UTF-8 encoded and just be a 307 redirect to Wizards? Surely only one of these is true.

**Comment by lunakv** [comment]
Let me clarify. All *content* responses served by AR (the parsed rules, glossary, raw text files, etc.) are in UTF-8. The `/link` routes specifically don't follow this rule, because they do not serve any AR-hosted content, but simply redirect to other sites.

**Comment by lunakv** [comment]
This is also spelled out in the [API docs](https://api.academyruins.com/docs#section/Response-Encoding-and-Formatting), but if you feel the docs are unclear, I would very much appreciate any suggestions on what to clarify.

**Comment by lunakv** [comment]
Are the changes from #182 live yet? It has been two weeks and the bot still doesn't work, while my local instance serves the CR successfully.

**Comment by multimeric** [comment]
We did deploy master since the PR. It isn't clear why this would not work.

**Comment by lunakv** [comment]
Do you have any build/runtime logs? Does the updateInteractions script get run on new deployments? Can someone else verify they can get the bot to work locally? I'd love to help, but I don't really have anything besides "it works for me, but not in production."

**Comment by multimeric** [comment]
@bra1n

**Comment by bra1n** [comment]
> Are the changes from #182 live yet? It has been two weeks and the bot still doesn't work, while my local instance serves the CR successfully.

Yes, the changes are live and the bot is not using any environment variables to overwrite CR_ADDRESS. So it seems like the bot pulls the CR from https://api.academyruins.com/link/cr, which redirects to https://media.wizards.com/2022/downloads/MagicCompRules%2020221118.txt

And to answer the second question: there are no log outputs except the usual:
> 0|judgebot | [22/12/03 19:00:04] [INFO] [bot-1237843] - booting up...
> 0|judgebot | [22/12/03 19:00:05] [INFO] [standard-1237843] - Standard is cached
> 0|judgebot | [22/12/03 19:00:05] [INFO] [ipg-1237843] - IPG Successfully Parsed
> 0|judgebot | [22/12/03 19:00:06] [INFO] [cr-1237843] - CR Ready, effective 
> 0|judgebot | [22/12/03 19:00:07] [INFO] [mtr-1237843] - MTR Ready
> 0|judgebot | [22/12/03 19:00:32] [INFO] [bot-1237843] - Bot is ready! Username: judgebot / Servers: 4513

**Comment by lunakv** [comment]
Actually, that's helpful. The CR doesn't print an effective date, which confirms the file still isn't getting parsed. I have a few theories, I'll try to do some digging and report back

**Comment by lunakv** [comment]
Okay, I don't have any really promising leads as of yet, so let's just start with the stupid stuff.
- What version of Node is the server running?
- When did you last run `npm install`?
- When did you last run `npm run build`?

The only thing even remotely interesting I ran across was a deprecation notice, which I fixed in #185.

**Comment by bra1n** [comment]
> * What version of Node is the server running?

v16.17.0

> * When did you last run `npm install`?

```
$ npm i
up to date, audited 327 packages in 3s
```

> * When did you last run `npm run build`?

That seems to have fixed it!

**Comment by lunakv** [comment]
Ah yes, always fun to lose your mind debugging your code, only to realize you're not actually running the code you're debugging (totally haven't done that a hundred times myself, no-siree! :laughing:). Happy to see the bot working again!

**Comment by bra1n** [comment]
Yes, sorry about that. 😬
