### ISSUE TITLE
[Question] Branches

### ISSUE THREAD

**Issue by lunakv** [bra1n/judgebot#184]
I just noticed that there are two branches, `develop` and `master`. Based on past pull requests, am I correct in assuming the production server is run off of `master` and new changes should be merged from feature branches into `develop` first, and only from there is `master` updated? It's not written down anywhere, so I'm left guessing.

**Comment by lunakv** [comment]
Oh, just noticed your comment under my PR :slightly_smiling_face: Sorry, will keep that in mind for future PRs. It would be nice to write this down in the README somewhere though.

**Comment by multimeric** [comment]
> I just noticed that there are two branches, `develop` and `master`. Based on past pull requests, am I correct in assuming the production server is run off of `master` and new changes should be merged from feature branches into `develop` first, and only from there is `master` updated? It's not written down anywhere, so I'm left guessing.

Your understanding is correct.
