### ISSUE TITLE
!card: Show the available formats that a card is legal in

### ISSUE THREAD

**Issue by bra1n** [bra1n/judgebot#28]
Should probably be limited to Vintage, Legacy, Modern and Standard. (instead of every block-format)

**Comment by hcschild** [comment]
And Commander?

**Comment by bra1n** [comment]
Commander is not supported by the API. :(

**Comment by hcschild** [comment]
It's listed in the legality array. :o

**Comment by bra1n** [comment]
Oops, my bad. :nerd_face:

**Comment by bra1n** [comment]
Looks good to me! Thanks @hcschild
