### ISSUE TITLE
!cr should support pulls of subrules

### ISSUE THREAD

**Issue by hugarh** [bra1n/judgebot#34]
While the bot is great, a large number of rules in mtg are split into several smaller subrules

Either allowing an option to simply return all subrules of the requested rule, or allowing multiple arguments to !cr would be useful when explaining a full rule to someone, instead of the rule being returned with breaks as you request each subrule in a seperate !cr

**Comment by bra1n** [comment]
That could lead to very long messages, so we'd probably have to cut off the subrules at some point... but I think it makes sense to support some kind of query that outputs more than one (sub)rule.
