### ISSUE TITLE
Switch away from the annotated IPG for !ipg

### ISSUE THREAD

**Issue by hgarus** [bra1n/judgebot#35]
As mentioned in #32, I think the version of the IPG available under https://sites.google.com/site/mtgfamiliar/rules/ is easier to parse, it also provides the whole IPG on a single page, which makes it simpler to read it in once on startup, so the bot doesn't have to make a separate request on each !ipg command.

**Comment by hcschild** [comment]
Thanks I will look into this.

**Comment by hgarus** [comment]
I have already done some work on this. I will send a pull request this evening.

**Comment by bra1n** [comment]
Fixed with #36
