### ISSUE TITLE
Implement !mtr

### ISSUE THREAD

**Issue by hgarus** [bra1n/judgebot#37]
Implement `!mtr [section]` based on the mtr from http://www.bluewizard.net/judgeDocs.html

**Comment by bra1n** [comment]
This will close #11 as well. :)

**Comment by bra1n** [comment]
`!mtr 10.4` outputs the changelog at the moment

**Comment by hgarus** [comment]
`!mtr 10.4` looks ok now. The answer gets truncated before the changelog would be displayed. In addition Ryan Stapleton removed the Changelog from the original HTML.
