### ISSUE TITLE
Bug with !hangman

### ISSUE THREAD

**Issue by KevinBaudin** [bra1n/judgebot#77]
We use judgebot on our Discord server, and hangman always gives us 

```
Error
You can only start one hangman game every 3 minutes.
```

It has worked before, but seems broken now

**Comment by bra1n** [comment]
Can you please give it a try again? It works for me and the bot is restarted every 24h, so it could be that it got stuck somehow and now it works again.

**Comment by KevinBaudin** [comment]
Yup, sorry, forgot to answer.
Yes, it probably got stuck, now it's ok again, and no bug since the report 2 weeks ago.
Thanks 👍

**Comment by bra1n** [comment]
Cool, thanks. :-)

**Comment by harryfino** [comment]
@bra1n the bot is doing this again on my server.

**Comment by bra1n** [comment]
> @bra1n the bot is doing this again on my server.

Weird, I just tested it and it worked fine. What did you do with the bot leading up to getting it stuck on hangman?
