### ISSUE TITLE
Clickable thumbnail image when using !card

### ISSUE THREAD

**Issue by tonini** [bra1n/judgebot#79]
Hi @bra1n 
Thanks for your great work with judgebot. :)

I really would like to be able to click on the thumbnail like when using `!hangman` and failing, it would be nice to have the ability to zoom into the card image/art. (https://github.com/bra1n/judgebot/blob/develop/modules/card.js#L241)

What do you think, shouldn't be that hard to implement?

Cheers

Sam

**Comment by bra1n** [comment]
Hi @tonini,

thanks for the suggestion, I'll look into it when I have some time. Unfortunately, I expect that Discord doesn't offer the means to allow zooming into thumbnails. With `!hangman`, the full image is actually attached with the response, which is something I'd rather avoid for regular `!card` queries. What I could add would be something like an `!image` command that returns (just) the card image in a higher resolution and with zoom functionality.

**Comment by bra1n** [comment]
Card images can be zoomed with the magnifying glass reaction now. :)
