### ISSUE TITLE
Image doesn't show in !hangman

### ISSUE THREAD

**Issue by Shardot** [bra1n/judgebot#80]
Hi.
The cardimage currently doesn't show up after completing a game of hangman. The issue seems to be that scryfall have changed their api.

Changing card.image_uri on row 78 in hangman.js to one of the following should fix it as far as I can tell:

card.image_uris.small
card.image_uris.normal
card.image_uris.large
card.image_uris.png

some cards also seems to have
card.image_uris.art_crop
and
card.image_uris.bordercrop
but not all of them.

**Comment by bra1n** [comment]
Thanks for the report @Shardot, fixed with #81
