### ISSUE TITLE
Consider allowing conditional support for [[CARD NAME]]

### ISSUE THREAD

**Issue by cryptiklemur** [bra1n/judgebot#86]
Would be pretty nice to have the bot listening for people who type things like `[[Hive Stone]]`, and respond with the proper card, and allow it to be configurable per server (toggle it on or off)

**Comment by bra1n** [comment]
That would require individual server settings, which would require some kind of configuration interface and config storage, plus the headache of who should be able to configure the bot. So far, I haven't seen enough advantages for server-specific settings to outweigh the extra work required to be able to configure the bot.
Feel free to build something like that and submit a PR though. :D

**Comment by cryptiklemur** [comment]
Wouldn't necessarily need to be configurable, just a nice thing for people

**Comment by bra1n** [comment]
Simply being able to turn this on or off would be already a configuration, because by default, Judgebot should not use the same syntax as the Scryfall bot. ;)

**Comment by cryptiklemur** [comment]
I mean, it doesn't need the option to turn it on or off, if its a bunch of extra work

**Comment by bra1n** [comment]
But then, like I said, Judgebot would have conflicting syntax with the Scryfall bot. And that just so people can type `[[hive stone]]` instead of `!card hive stone!`? Maybe if there's enough demand...

**Comment by bra1n** [comment]
Not going to add this anytime soon.
