### ISSUE TITLE
!card function is imprecise

### ISSUE THREAD

**Issue by Nullzone42** [bra1n/judgebot#87]
When querying judgebot using !card we frequently get an undesired result - near as I can figure it seems to be indexing all possible matches for the search term and then returning the first match in the index, even if there's a more exacting comparison.

For example, !card fling (or !card Fling) returns Akki Boneflinger, rather than Fling. If I was making a deliberate imprecise search, I'd expect to be including wildcards - the implicit wildcard search makes it impossible to get simple-worded cards from the bot.

**Comment by bra1n** [comment]
Weird, if I use `!card fling`, I get Fling as the first result:
![fling](https://i.imgur.com/5wdMVzM.png)
Is there any other query where you get these imprecise results?

**Comment by Nullzone42** [comment]
Most one-word card names seem to do this, particularly if they don't start with A. Just in the last few minutes I've hit Moat (got Magus of the Moat), Opt (got Flowstone Thopter), Recall (Ancestral Recall), Wonder (Bazaar of Wonders)...you get the idea.

Of note, in case it's significant: when I was testing the different capitalization on Fling I tried using the "arrow react" to cycle the output to Fling itself, mainly out of curiosity since I'd never tried using that feature before, and now when I query fling it does in fact return Fling proper by default. I don't know if this causes the bot to weight or associate the word any differently somehow.

**Comment by bra1n** [comment]
Alright, I can reproduce the issue with "!card opt". Take a look at the [API from Scryfall](https://api.scryfall.com/cards/search?q=opt ), which Judgebot is using, or [the actual Scryfall site](https://scryfall.com/search?q=opt). In both cases, the card "Opt" is not the first result. This means, Judgebot would need some additional code to sort 100% matching cards to the front. Currently, Scryfall only provides sorting by name, set, etc. but not by "result relevance".

**Comment by Nullzone42** [comment]
Gotcha. Maybe this is more a feature request than a bug then? It's still awkward in practice (especially when the actual scryfall bot has not shown similar problems parsing single word cards).

**Comment by bra1n** [comment]
Alright, I've just committed a fix for this issue that should sort perfect matches (like "opt") always to the top and after that prefer matches at the beginning of the name followed by matches that have the highest relation of query length vs card name length.
