### ISSUE TITLE
Documents are outdated

### ISSUE THREAD

**Issue by KingSupernova31** [bra1n/judgebot#92]
The bot is still using the Ixalan rules documents.

**Comment by bra1n** [comment]
Hi @KingSupernova31,
thanks for the report! Unfortunately, the base files for the rules lookup, which so far have been kindly provided by the MTG Familiar app / [Blue Wizard](http://www.bluewizard.net/judgeDocs.html) are no longer being updated, so we'll have to look into viable alternatives. This should be somewhat easy to fix for the CR (as WotC provides them in TXT format), but will be a lot harder for the MTR and IPG docs...
I'll update the ticket when we have a solution.

**Comment by bra1n** [comment]
Alright, IPG and CR have been fixed. MTR still needs to be worked on.

**Comment by AEFeinstein** [comment]
MTG Familiar maintainer here. I ended up writing a tool to collate the docs from https://blogs.magicjudges.org/rules/ into single page HTML. They're still in a branch, but you can see the results here:
https://github.com/AEFeinstein/GathererScraper/tree/new-judge-docs/rules
Once those get merged into master, I'll be maintaining them for as long as magicjudges.org does (or you can use my tool to generate the html yourself).

**Comment by bra1n** [comment]
Cool, thanks for the effort @AEFeinstein! I'll take a look and if it's easier to use than the PDFs, we'll switch to them. :)

**Comment by AEFeinstein** [comment]
FYI, the rules now live at https://github.com/AEFeinstein/GathererScraper/tree/master/rules
And if you want to generate the files yourself, you can run the program and click the "Scrape Judge Docs" button. You could automate it further if you want, I made an RSS feed which posts when there are new docs at https://mtgfamiliar.shick.xyz/gatherer_sets.rss

**Comment by bra1n** [comment]
Cheers, I've just updated the MTR link.

**Comment by Shoe2** [comment]
So, is this still a problem? As far as I can tell the comp rules are over 6 months old now rendering most of the bot useless.

**Comment by bra1n** [comment]
I actually wanted to wait with the deployment until #128 was done, but since you really seem to need the updated CR, I deployed it now. ;-)

**Comment by n21lv** [comment]
If anything, there is probably a better source of CR to be found at https://yawgatog.com/resources/magic-rules/. That gets updated much faster than CR (I think automatically) at https://blogs.magicjudges.org/rules/cr/ and is hyperlinked to the brim.

**Comment by bra1n** [comment]
> If anything, there is probably a better source of CR to be found at https://yawgatog.com/resources/magic-rules/. That gets updated much faster than CR (I think automatically) at https://blogs.magicjudges.org/rules/cr/ and is hyperlinked to the brim.

Unfortunately, the rules document needs to be parsable by the bot, so having hyperlinks or additional (html) markup makes it unusable to the bot. And Wizards always has to update their CR URL, sometimes even changing the format of the file every other release, so I always have to update the code by hand.

**Comment by n21lv** [comment]
Hmm.. can't you just grab the text via HTMLElement.innerText after locating the necessary rule via ID? E.g. : 
```
function getCR(ruleNum) {
    let ruleId = '#R' + ruleNum.replace('.','');
    let fullText = $(ruleId)[0].parentNode.innerText;
    const regex = /^([\d\.a-z]+)(.*)$/gm;
    let result = [...fullText.matchAll(regex)];
    return { number, text } = [ result[0][1], (result[0][2]).trim() ];
}

getCR('704.5m');
// RESULT:
// ["704.5m.", "If an Aura is attached to an illegal object or pla…yer, that Aura is put into its owner's graveyard."]
```
UPD: updated the example slightly

**Comment by KingSupernova31** [comment]
Just use https://slack.vensersjournal.com/allrules, or if that isn't formatted the way you want, ask Andrew to add a different endpoint.

**Comment by bra1n** [comment]
Finally, thanks to #140 and @Villawhatever, this should no longer be an issue. :-)
